// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MyEnum int32

const (
	MyEnum_ValueA MyEnum = 0
	MyEnum_ValueB MyEnum = 1
)

var MyEnum_name = map[int32]string{
	0: "ValueA",
	1: "ValueB",
}

var MyEnum_value = map[string]int32{
	"ValueA": 0,
	"ValueB": 1,
}

func (x MyEnum) String() string {
	return proto.EnumName(MyEnum_name, int32(x))
}

func (MyEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

type MyMessage struct {
	Test1                MyEnum   `protobuf:"varint,1,opt,name=test1,proto3,enum=MyEnum" json:"test1,omitempty"`
	Test2                uint32   `protobuf:"varint,2,opt,name=test2,proto3" json:"test2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyMessage) Reset()         { *m = MyMessage{} }
func (m *MyMessage) String() string { return proto.CompactTextString(m) }
func (*MyMessage) ProtoMessage()    {}
func (*MyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *MyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyMessage.Unmarshal(m, b)
}
func (m *MyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyMessage.Marshal(b, m, deterministic)
}
func (m *MyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyMessage.Merge(m, src)
}
func (m *MyMessage) XXX_Size() int {
	return xxx_messageInfo_MyMessage.Size(m)
}
func (m *MyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MyMessage proto.InternalMessageInfo

func (m *MyMessage) GetTest1() MyEnum {
	if m != nil {
		return m.Test1
	}
	return MyEnum_ValueA
}

func (m *MyMessage) GetTest2() uint32 {
	if m != nil {
		return m.Test2
	}
	return 0
}

func init() {
	proto.RegisterEnum("MyEnum", MyEnum_name, MyEnum_value)
	proto.RegisterType((*MyMessage)(nil), "MyMessage")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x72, 0xe0, 0xe2, 0xf4, 0xad, 0xf4, 0x4d, 0x2d,
	0x2e, 0x4e, 0x4c, 0x4f, 0x15, 0x92, 0xe5, 0x62, 0x2d, 0x49, 0x2d, 0x2e, 0x31, 0x94, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x33, 0x62, 0xd7, 0xf3, 0xad, 0x74, 0xcd, 0x2b, 0xcd, 0x0d, 0x82, 0x88, 0x0a,
	0x89, 0x40, 0xa4, 0x8d, 0x24, 0x98, 0x14, 0x18, 0x35, 0x78, 0x21, 0xa2, 0x46, 0x5a, 0x0a, 0x5c,
	0x6c, 0x10, 0x65, 0x42, 0x5c, 0x5c, 0x6c, 0x61, 0x89, 0x39, 0xa5, 0xa9, 0x8e, 0x02, 0x0c, 0x70,
	0xb6, 0x93, 0x00, 0x63, 0x12, 0x1b, 0xd8, 0x2a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19,
	0x9c, 0xc7, 0x1d, 0x79, 0x00, 0x00, 0x00,
}
